import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Platform", description: "Intelligence with operational context." };
const capabilities = [["01", "Signal synthesis", "Bring regulatory, infrastructure, competitor, consumer, and market signals into one operating view."], ["02", "Explainable confidence", "Every insight carries a confidence score, source lineage, and temporal context your team can interrogate."], ["03", "Actionable response", "Move from fragmented information to decision-ready recommendations before the window closes."]];

export default function PlatformPage() {
  return <><section className="bg-[#f3f5ff] py-20 sm:py-28"><div className="site-shell grid gap-16 lg:grid-cols-[.9fr_1.1fr] lg:gap-28"><div><p data-reveal className="eyebrow">The platform</p><h1 data-text-reveal className="editorial-display mt-6 max-w-[9ch] text-5xl leading-[.98] sm:text-6xl lg:text-7xl">Intelligence with <em>operational context.</em></h1><p data-reveal className="mt-8 max-w-[32ch] text-sm leading-7 text-deep-ink/65 sm:text-base">Designed around the market realities that define African financial services—not generic global assumptions.</p></div><div data-stagger className="border-t border-deep-ink/20">{capabilities.map(([number,title,text]) => <article key={number} className="grid grid-cols-[52px_1fr_auto] gap-4 border-b border-deep-ink/20 py-7 transition hover:pl-2 sm:py-9"><span className="pt-1 text-xs font-bold text-primary-blue/80">{number}</span><div><h2 className="text-xl font-bold tracking-tight sm:text-2xl">{title}</h2><p className="mt-3 max-w-[54ch] text-sm leading-6 text-deep-ink/65">{text}</p></div><span className="text-primary-blue">↗</span></article>)}</div></div></section>
  <section className="dark-grid bg-[#081330] py-20 text-white sm:py-28"><div className="site-shell grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><div><p data-reveal className="eyebrow-light">An intelligence operating system</p><h2 data-text-reveal className="editorial-display mt-5 text-5xl leading-[.98] sm:text-6xl">Not more data.<br/><em>More certainty.</em></h2><p data-reveal className="mt-7 max-w-[36ch] text-sm leading-7 text-white/60">Turn noisy, time-sensitive market movements into a shared basis for product, growth, operations, and strategy decisions.</p></div><div data-stagger className="overflow-hidden border border-white/15"><div className="grid grid-cols-[1fr_1.3fr_.7fr_.7fr] border-b border-white/15 px-5 py-4 text-[9px] font-bold uppercase tracking-[.15em] text-blue-200/60"><span>Source</span><span>Signal</span><span>Priority</span><span>Confidence</span></div>{[["CBN","Policy signal","High","92%"],["NIBSS","Settlement stability","Monitor","86%"],["Market","Competitor movement","High","88%"]].map(([source,signal,priority,confidence]) => <div key={source} className="grid grid-cols-[1fr_1.3fr_.7fr_.7fr] items-center border-b border-white/10 px-5 py-5 text-xs text-white/75"><b className="text-white">● &nbsp;{source}</b><span>{signal}</span><span className={priority === "High" ? "text-rose-300" : "text-amber-200"}>{priority}</span><b className="text-[#7f8bff]">{confidence}</b></div>)}<div className="flex items-center justify-between px-5 py-5 text-xs text-white/55"><span>Signal field updated continuously</span><Link href="/waitlist" className="text-white transition hover:text-primary-blue">Open intelligence map &nbsp;→</Link></div></div></div></section>
  <section className="site-shell py-20 text-center sm:py-28"><p data-reveal className="eyebrow">What arrives with every brief</p><div data-stagger className="mt-10 grid text-left sm:grid-cols-3">{[["01","What changed","A focused account of the movement that deserves attention."],["02","Why it matters","Evidence, local context, and a confidence level your team can question."],["03","What to do next","A decision-ready prompt designed for your operating reality."]].map(([n,title,text]) => <div key={n} className="border border-deep-ink/15 p-7 transition hover:bg-[#f3f5ff]"><p className="text-xs font-bold text-primary-blue">{n}</p><h3 className="mt-7 text-2xl font-serif">{title}</h3><p className="mt-4 text-sm leading-6 text-deep-ink/60">{text}</p></div>)}</div></section></>;
}
