import Link from "next/link";

const moments = [
  ["◎", "Regulation change", "New directives and enforcement patterns before they disrupt your roadmap."],
  ["◌", "Competitor move", "Product launches, pricing shifts and partnerships as they unfold."],
  ["⌁", "Infrastructure event", "Payment and network events that affect uptime and customers."],
];

function IntelligenceBrief() {
  return (
    <div data-brief className="relative mx-auto max-w-[500px] border border-[#6d7aaa]/40 bg-[#0d1733]/90 p-5 text-white shadow-[0_28px_90px_rgba(0,0,0,.42)] sm:p-6">
      <div className="flex items-center justify-between text-[9px] font-semibold uppercase tracking-[.14em] text-blue-200/65">
        <span>◀ Intelligence brief</span><span>09:42 WAT · 18 May 2026</span>
      </div>
      <h2 className="mt-6 text-xl font-serif sm:text-2xl"><span className="text-primary-blue">⌁</span> Settlement pattern detected</h2>
      <p className="mt-3 text-xs leading-5 text-blue-100/75 sm:text-sm">Unusual concentration in weekend settlement activity across 3 acquiring banks and 2 PSPs.</p>
      <div className="mt-5 border border-[#536184]/30 bg-[#111d3b] p-4">
        <p className="text-[9px] font-bold uppercase tracking-[.14em] text-blue-200/60">Confidence score</p>
        <div className="mt-2 flex items-end justify-between"><p className="text-3xl font-light text-[#24a0ff]"><span data-counter="86">86</span><span className="ml-1 text-xs text-white/60">/ 100</span></p><p className="text-right text-xs text-[#6bd1ff]">High<br/><span className="text-[9px] text-white/45">↑ 24 pts vs last 7 days</span></p></div>
      </div>
      <div className="mt-5"><p className="text-[9px] font-bold uppercase tracking-[.14em] text-blue-200/60">Source lineage</p><div className="mt-3 grid grid-cols-4 gap-2 text-center text-[9px] text-white/70"><span className="border border-white/10 p-2">NIBSS</span><span className="border border-white/10 p-2">CBN</span><span className="border border-white/10 p-2">USSD</span><span className="border border-white/10 p-2">+7</span></div></div>
      <div className="mt-5 flex gap-3 border-t border-white/10 pt-4"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-primary-blue">→</span><p className="text-xs leading-5 text-white/75"><b className="block text-[9px] uppercase tracking-[.12em] text-blue-200/65">Recommended next move</b>Review weekend settlement limits and liquidity buffers.</p></div>
    </div>
  );
}

export function HomeClient() {
  return (
    <div>
      <section className="dark-grid overflow-hidden bg-[#050a1b] text-white">
        <div className="site-shell grid min-h-[690px] items-center gap-14 py-20 lg:grid-cols-[.92fr_1.08fr] lg:py-24">
          <div><p data-reveal className="eyebrow-light">The signal</p><h1 data-text-reveal className="editorial-display mt-5 max-w-[10ch] text-5xl leading-[.98] sm:text-6xl lg:text-7xl">What changed while you were looking <em className="not-italic text-primary-blue">elsewhere.</em></h1><p data-reveal className="mt-7 max-w-[45ch] text-sm leading-6 text-white/65 sm:text-base">Stem Cogent is Nigeria-first intelligence for fintech and financial-services leaders. We turn signals others miss into validated, explainable intelligence you can act on.</p><div data-reveal className="mt-9 flex flex-wrap gap-x-7 gap-y-4 text-xs text-white/80"><span>◎ <b className="ml-2">Early signals</b></span><span>◇ <b className="ml-2">Explainable</b></span><span>◯ <b className="ml-2">Decision-ready</b></span></div></div>
          <div className="relative"><div className="absolute -inset-20 bg-[radial-gradient(circle,rgba(51,60,255,.24),transparent_57%)]"/><IntelligenceBrief /></div>
        </div>
        <div className="border-t border-white/15 py-5 text-center text-xs tracking-[.24em] text-white/70 sm:text-sm">VALIDATED <span className="mx-3 text-primary-blue">·</span> EXPLAINABLE <span className="mx-3 text-primary-blue">·</span> REGIONALLY REAL <span className="mx-3 text-primary-blue">·</span> DECISION-READY</div>
      </section>

      <section className="site-shell py-20 text-center sm:py-28"><p data-reveal className="eyebrow">What matters most</p><h2 data-text-reveal className="editorial-display mt-3 text-4xl sm:text-5xl">The decisions that cannot wait.</h2><p data-reveal className="mt-3 text-sm text-deep-ink/60">Three intelligence moments that shape outcomes in financial services.</p><div data-stagger className="mt-11 grid gap-4 text-left md:grid-cols-3">{moments.map(([icon,title,text]) => <article key={title} className="border border-deep-ink/10 bg-white p-7 shadow-[0_12px_28px_rgba(20,30,60,.05)] transition duration-300 hover:-translate-y-1 hover:shadow-[0_22px_36px_rgba(20,30,60,.10)]"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-[#edf2ff] text-lg text-primary-blue">{icon}</span><h3 className="mt-5 text-lg font-serif">{title}</h3><p className="mt-4 text-xs leading-5 text-deep-ink/60">{text}</p><span className="mt-6 inline-block text-xs font-semibold text-primary-blue">Explore &nbsp;→</span></article>)}</div></section>

      <section className="dark-grid overflow-hidden bg-[#07112b] py-20 text-white sm:py-28"><div className="site-shell"><div className="text-center"><p data-reveal className="eyebrow-light">Our system</p><h2 data-text-reveal className="editorial-display mt-3 text-4xl sm:text-5xl">From signal to decision.</h2><p data-reveal className="mt-3 text-sm text-white/60">A repeatable intelligence system built for Nigeria’s financial ecosystem.</p></div><div data-stagger className="mt-14 grid gap-9 text-center md:grid-cols-3">{[["1","Detect","We scan policy, payments, infrastructure, markets and behaviour."],["2","Validate","We validate what matters with source lineage and confidence scoring."],["3","Act","You receive clear intelligence briefs built for your context."]].map(([n,title,text]) => <div key={n}><span className="mx-auto flex h-9 w-9 items-center justify-center rounded-full border border-primary-blue text-sm text-blue-200">{n}</span><h3 className="mt-5 font-serif text-xl">{title}</h3><p className="mx-auto mt-3 max-w-[27ch] text-xs leading-5 text-white/55">{text}</p></div>)}</div><div data-reveal className="mt-14 grid gap-5 md:grid-cols-[1fr_170px_1fr] md:items-center"><div className="border border-white/15 bg-white/5 p-5"><p className="eyebrow-light !text-[9px]">Signals in</p><ul className="mt-4 space-y-2 text-xs text-white/65"><li>▦ Market movements</li><li>▦ Policy changes</li><li>▦ Infrastructure events</li><li>▦ Competitor behaviour</li></ul></div><div className="text-center text-primary-blue"><div data-engine className="text-5xl">◉</div><p className="mt-2 text-[10px] tracking-[.16em] text-white/60">STEM COGENT<br/>Intelligence Engine</p></div><div className="border border-white/15 bg-white/5 p-5"><p className="eyebrow-light !text-[9px]">Decision out</p><ul className="mt-4 space-y-2 text-xs text-white/65"><li>◉ Validated brief</li><li>◉ Confidence score</li><li>◉ Source lineage</li><li>◉ Recommended move</li></ul></div></div></div></section>

      <section className="bg-[#f3f6ff] py-20 sm:py-28"><div className="site-shell"><div className="mx-auto max-w-3xl text-center"><p data-reveal className="eyebrow">Built for accountable teams</p><h2 data-text-reveal className="editorial-display mt-3 text-4xl sm:text-5xl">Know what matters. Defend the decision. Move in time.</h2><p data-reveal className="mt-5 text-sm leading-6 text-deep-ink/60">Stem Cogent gives strategy, growth, product, and risk leaders a shared intelligence layer before a market change becomes an expensive surprise.</p></div><div data-stagger className="mt-12 grid gap-4 md:grid-cols-3">{[["01","A clearer brief before the meeting.","Bring the signal, its implications, and the evidence into one decision-ready view."],["02","Confidence your leadership can interrogate.","Every insight carries context and source lineage—so teams can challenge the conclusion, not chase the facts."],["03","Fewer blind spots. Better timing.","See the move early enough to protect a plan, adjust a position, or take the opportunity first."]].map(([n,title,text]) => <article key={n} className="border border-deep-ink/10 bg-white p-7 transition duration-300 hover:-translate-y-1 hover:shadow-[0_22px_36px_rgba(20,30,60,.10)]"><span className="text-xs font-bold text-primary-blue">{n}</span><h3 className="mt-8 text-2xl font-serif">{title}</h3><p className="mt-4 text-sm leading-6 text-deep-ink/60">{text}</p></article>)}</div></div></section>

      <section className="blue-grid bg-primary-blue py-20 text-white sm:py-24"><div className="site-shell grid gap-10 md:grid-cols-[1.2fr_.8fr] md:items-end"><div><p data-reveal className="eyebrow-light">Private access · Launching soon</p><h2 data-text-reveal className="editorial-display mt-4 max-w-[13ch] text-5xl leading-[.98] sm:text-6xl">Make your next move <em>the informed one.</em></h2><p data-reveal className="mt-5 max-w-[45ch] text-sm leading-6 text-white/80">Join the Stem Cogent waitlist for early platform access and launch updates.</p></div><div data-reveal className="border-l border-white/35 pl-7"><ul className="space-y-3 text-xs text-white/90"><li>◉ Early access to the platform</li><li>◉ Shape features with your input</li><li>◉ Priority onboarding</li></ul><Link href="/waitlist" className="mt-7 inline-flex bg-white px-5 py-3 text-sm font-semibold text-primary-blue transition hover:-translate-y-1 hover:shadow-xl">Become a founding customer <span className="ml-3">→</span></Link></div></div></section>
    </div>
  );
}
